GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5e6534eeaeae6b1cfc74af93


###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Arnold Swartza",
    "subscribedToChannel":"I mizz da Austria"
}